### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by mtozlu** [dro123/redmine_meeting_room_calendar#12]
Hi, i have translated this plugin into Turkish. Here is the translation:

```
# Turkish strings go here for Rails i18n
tr:
  label_name: "Toplantı Odası Rezervasyon"
  label_meeting_date: "Tarih"
  label_booked_by: "Rezerve eden"
  label_assigned_to: "İlgili kişi"
  label_assigne_to: "Kişiye ata"
  label_category: "Kategori"
  label_start_time: "Başlangıç"
  label_end_time: "Bitiş"
  label_info: "Bilgi"
  label_alert: "Uyarı"
  label_warning_edit_past: "Geçmiş rezervasyonları değiştiremezsiniz"
  label_warning_create_past: "Geçmiş zamanda bir rezervasyon yapamazsınız"
  label_warning_update_past: "Rezervasyonu, geçmiş zamanı içerecek şekilde değiştiremezsiniz"
  label_warning_weekend: "Hafta sonu rezervasyon yapamazsınız"
  label_warning_fields_mandatory: "Bütün alanlar doldurulmalıdır"
  label_update_event: "Rezervasyonu güncelle"
  label_create_event: "Rezervasyon yap"
  label_invalid_subject: "Geçerli bir konu girin"
  label_room_already_booked: "Seçilen vakitlerde oda rezerve edilmiş"
  label_goto: "Git"
  label_project: "Proje"
  label_meeting_room: "Toplantı Odası"
  label_subject: "Konu"
  label_recur: "Tekrarla"
  label_save: "Kaydet"
  label_delete: "Sil"
  label_today: "Bugün"
  label_day: "Gün"
  label_week: "Hafta"
  label_month: "Ay"
  label_weekly: "Haftalık"
  label_biweekly: "İki haftalık"
  label_daily: "Günlük"
  label_count: "kere"
  label_missing_config: "Eklenti doğru yapılandırılmamış! Yönetim -> Eklentiler -> Yapılandır'a gidiniz"
  label_setting_project_id: "Proje"
  label_setting_tracker_id: "İş Tipi"
  label_setting_custom_field_id_room: "'Oda' Özel Alanı"
  label_setting_custom_field_id_start: "'Başlangıç' Özel Alanı"
  label_setting_custom_field_id_end: "'Bitiş' Özel Alanı"
  label_setting_issue_status_id: "İş durumu"
  label_setting_show_project_menu: "Proje menüsünü göster"
  label_setting_show_categories: "Kategori seçimini göster"
  label_setting_hide_projects: "Proje seçimini gizle"
  label_setting_hide_rooms: "Oda seçimini gizle"
  label_setting_allow_changing_old_meetings: "Geçmiş rezervasyonları değiştirmeye müsade et"
  label_setting_allow_drag_and_drop: "Rezervasyonları fare ile sürükleme ve bırakmaya müsade et"
  label_setting_allow_resize: "Rezervasyon tarihlerini fare ile çekerek değiştirmeye müsade et"

  field_project_meeting_rooms: "Odalar (virgülle ayrılmış)"

  datetime_title_format_day: "dddd, MMM d, yyyy"
  datetime_title_format_week: "MMM d[ yyyy]{ -[ MMM] d yyyy}"
  datetime_title_format_month: "MMMM yyyy"
  datetime_column_format_day: "ddd"
  datetime_column_format_week: "ddd M/d"
  datetime_column_format_month: "dddd M/d"
  datetime_entry_format_time: "h(:mm)t"

  day_names: " ['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi', 'Pazar']"
  abbr_day_names: "['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz']"
  month_names: "['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık']"
  abbr_month_names: "['Oca','Şub','Mar','Nis','May','Haz','Tem','Ağu','Eyl','Eki','Kas','Ara']"
  first_day: 0
  date_format: "mm/dd/yy"

  datetime_min: "6:00am"
  datetime_max: "9:00pm"
  datetime_time_format: "HH:mm"
```
